# Generated by Django 5.2.1 on 2025-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('salario_mensal', models.FloatField()),
                ('score_credito', models.FloatField()),
                ('tempo_emprego_anos', models.FloatField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('possui_imovel', models.BooleanField()),
                ('possui_veiculo', models.BooleanField()),
                ('qtd_cartoes_credito', models.IntegerField()),
                ('historico_inadimplencia', models.BooleanField()),
                ('valor_credito_solicitado', models.FloatField()),
                ('dividas_banco_A', models.FloatField()),
                ('dividas_banco_B', models.FloatField()),
                ('dividas_banco_C', models.FloatField()),
                ('dividas_totais', models.FloatField()),
                ('score_risco', models.FloatField(blank=True, null=True)),
                ('aprovado_previsto', models.BooleanField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
